language : java
install: true

jdk: oraclejdk8

os: osx
dist : trusty

script:
  - ./gradlew build --scan -s

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/



